spin_manifest_version = 2

[application]
name = "survivor-draft"
version = "0.1.1"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = "Draft"

[variables]
season = { required = true }
draft_deadline = { default = "2025-09-25T03:00:00" } # format: "2024-09-25T03:00:00"
sqlite_username = { required = true }
sqlite_password = { required = true }

[[trigger.http]]
route = "/api/..."
component = "survivor-draft"

[component.survivor-draft]
source = "target/wasm32-wasi/release/survivor_draft.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.survivor-draft.variables]
season = "{{ season }}"
draft_deadline = "{{ draft_deadline }}"
[component.survivor-draft.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "static-fileserver"

[component.static-fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "assets", destination = "/" }]

[[trigger.http]]
component = "spin-sqlite-explorer"
route = "/internal/sqlite/..."

[component.spin-sqlite-explorer]
source = { url = "https://github.com/karthik2804/spin-sqlite-web-cli/releases/download/v0.1.0/spin-sqlite-web-cli.wasm", digest = "sha256:2bab8dca3c50bc082c543ce9e9b367aec03e9de1efd62c6b748035bd9de48356" }
sqlite_databases = ["default"]

[component.spin-sqlite-explorer.variables]
sqlite_username = "{{ sqlite_username }}"
sqlite_password = "{{ sqlite_password }}"
